name: Main Branch CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build 
      run: /home/runner/work/NtmOS/NtmOS/build.sh
      shell: bash
